import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:intl/intl.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/l10n/language_provider.dart';
import '../../auth/providers/auth_provider.dart';
import '../models/therapist_availability.dart';
import '../services/therapist_availability_service.dart';

/// Provider for availability service
final therapistAvailabilityServiceProvider =
    Provider<TherapistAvailabilityService>((ref) {
      return TherapistAvailabilityService();
    });

/// Provider for weekly template
final weeklyTemplateProvider = StreamProvider<WeeklyAvailability?>((ref) {
  final authState = ref.watch(authProvider);
  final service = ref.watch(therapistAvailabilityServiceProvider);

  if (authState.user?.uid == null) {
    return Stream.value(null);
  }

  return service.getWeeklyTemplateStream(authState.user!.uid);
});

/// Provider for availability slots in current week
final weeklyAvailabilityProvider =
    StreamProvider.family<List<AvailabilitySlot>, DateTime>((ref, weekStart) {
      final authState = ref.watch(authProvider);
      final service = ref.watch(therapistAvailabilityServiceProvider);

      if (authState.user?.uid == null) {
        return Stream.value([]);
      }

      final weekEnd = weekStart.add(const Duration(days: 7));
      return service.getAvailability(authState.user!.uid, weekStart, weekEnd);
    });

class TherapistAvailabilityScreen extends ConsumerStatefulWidget {
  const TherapistAvailabilityScreen({super.key});

  @override
  ConsumerState<TherapistAvailabilityScreen> createState() =>
      _TherapistAvailabilityScreenState();
}

class _TherapistAvailabilityScreenState
    extends ConsumerState<TherapistAvailabilityScreen> {
  late DateTime _selectedWeekStart;
  int _selectedDay = DateTime.now().weekday % 7;
  bool _isLoading = false;

  List<String> _getDayNames() {
    final s = ref.read(stringsProvider);
    return [s.sun, s.mon, s.tue, s.wed, s.thu, s.fri, s.sat];
  }

  @override
  void initState() {
    super.initState();
    final now = DateTime.now();
    _selectedWeekStart = now.subtract(Duration(days: now.weekday % 7));
  }

  @override
  Widget build(BuildContext context) {
    final strings = ref.watch(stringsProvider);
    final isDark = Theme.of(context).brightness == Brightness.dark;
    final weeklyTemplate = ref.watch(weeklyTemplateProvider);
    final slotsAsync = ref.watch(
      weeklyAvailabilityProvider(_selectedWeekStart),
    );

    return Scaffold(
      backgroundColor: isDark
          ? AppColors.backgroundDark
          : AppColors.backgroundLight,
      appBar: AppBar(
        title: Text(strings.manageAvailability),
        actions: [
          IconButton(
            icon: const Icon(Icons.auto_fix_high),
            tooltip: strings.autoGenerate,
            onPressed: () => _showAutoGenerateDialog(strings),
          ),
        ],
      ),
      body: Column(
        children: [
          // Week selector
          _buildWeekSelector(strings, isDark),

          // Day tabs
          _buildDayTabs(isDark),

          // Content area
          Expanded(
            child: weeklyTemplate.when(
              loading: () => const Center(child: CircularProgressIndicator()),
              error: (error, stack) =>
                  Center(child: Text(strings.errorLoadingData)),
              data: (template) {
                return slotsAsync.when(
                  loading: () =>
                      const Center(child: CircularProgressIndicator()),
                  error: (error, stack) =>
                      Center(child: Text(strings.errorLoadingData)),
                  data: (slots) {
                    return _buildDayContent(template, slots, strings, isDark);
                  },
                );
              },
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: () => _showAddSlotDialog(strings),
        icon: const Icon(Icons.add),
        label: Text(strings.addTimeSlot),
        backgroundColor: AppColors.primary,
      ),
    );
  }

  Widget _buildWeekSelector(S strings, bool isDark) {
    final weekEnd = _selectedWeekStart.add(const Duration(days: 6));
    final formatter = DateFormat('MMM d');

    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12),
      decoration: BoxDecoration(
        color: isDark ? AppColors.surfaceDark : Colors.white,
        boxShadow: [
          BoxShadow(
            color: Colors.black.withValues(alpha: 0.05),
            blurRadius: 4,
            offset: const Offset(0, 2),
          ),
        ],
      ),
      child: Row(
        mainAxisAlignment: MainAxisAlignment.spaceBetween,
        children: [
          IconButton(
            icon: const Icon(Icons.chevron_left),
            onPressed: () {
              setState(() {
                _selectedWeekStart = _selectedWeekStart.subtract(
                  const Duration(days: 7),
                );
              });
            },
          ),
          Text(
            '${formatter.format(_selectedWeekStart)} - ${formatter.format(weekEnd)}',
            style: TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.w600,
              color: isDark ? Colors.white : Colors.black87,
            ),
          ),
          IconButton(
            icon: const Icon(Icons.chevron_right),
            onPressed: () {
              setState(() {
                _selectedWeekStart = _selectedWeekStart.add(
                  const Duration(days: 7),
                );
              });
            },
          ),
        ],
      ),
    );
  }

  Widget _buildDayTabs(bool isDark) {
    return Container(
      height: 80,
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: ListView.builder(
        scrollDirection: Axis.horizontal,
        padding: const EdgeInsets.symmetric(horizontal: 12),
        itemCount: 7,
        itemBuilder: (context, index) {
          final date = _selectedWeekStart.add(Duration(days: index));
          final isSelected = index == _selectedDay;
          final isToday = _isToday(date);

          return GestureDetector(
            onTap: () {
              setState(() {
                _selectedDay = index;
              });
            },
            child: Container(
              width: 56,
              margin: const EdgeInsets.symmetric(horizontal: 4),
              decoration: BoxDecoration(
                color: isSelected
                    ? AppColors.primary
                    : (isDark ? AppColors.surfaceDark : Colors.white),
                borderRadius: BorderRadius.circular(12),
                border: isToday && !isSelected
                    ? Border.all(color: AppColors.primary, width: 2)
                    : null,
                boxShadow: isSelected
                    ? [
                        BoxShadow(
                          color: AppColors.primary.withValues(alpha: 0.3),
                          blurRadius: 8,
                          offset: const Offset(0, 4),
                        ),
                      ]
                    : null,
              ),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Text(
                    _getDayNames()[index],
                    style: TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.w500,
                      color: isSelected
                          ? Colors.white
                          : (isDark ? Colors.white60 : Colors.black54),
                    ),
                  ),
                  const SizedBox(height: 4),
                  Text(
                    date.day.toString(),
                    style: TextStyle(
                      fontSize: 18,
                      fontWeight: FontWeight.bold,
                      color: isSelected
                          ? Colors.white
                          : (isDark ? Colors.white : Colors.black87),
                    ),
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }

  Widget _buildDayContent(
    WeeklyAvailability? template,
    List<AvailabilitySlot> slots,
    S strings,
    bool isDark,
  ) {
    final selectedDate = _selectedWeekStart.add(Duration(days: _selectedDay));
    final daySlots = slots
        .where(
          (s) =>
              s.startTime.year == selectedDate.year &&
              s.startTime.month == selectedDate.month &&
              s.startTime.day == selectedDate.day,
        )
        .toList();

    daySlots.sort((a, b) => a.startTime.compareTo(b.startTime));

    // Get template time ranges for this day
    final templateRanges = template?.weeklySlots[_selectedDay] ?? [];

    return SingleChildScrollView(
      padding: const EdgeInsets.all(16),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          // Working hours section
          if (templateRanges.isNotEmpty) ...[
            Text(
              strings.workingHours,
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.bold,
                color: isDark ? Colors.white : Colors.black87,
              ),
            ),
            const SizedBox(height: 8),
            ...templateRanges.map(
              (range) => Container(
                margin: const EdgeInsets.only(bottom: 8),
                padding: const EdgeInsets.symmetric(
                  horizontal: 16,
                  vertical: 12,
                ),
                decoration: BoxDecoration(
                  color: AppColors.primary.withValues(alpha: 0.1),
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(
                    color: AppColors.primary.withValues(alpha: 0.3),
                  ),
                ),
                child: Row(
                  children: [
                    Icon(Icons.schedule, size: 20, color: AppColors.primary),
                    const SizedBox(width: 12),
                    Text(
                      range.formatted,
                      style: TextStyle(
                        fontWeight: FontWeight.w600,
                        color: isDark ? Colors.white : Colors.black87,
                      ),
                    ),
                    const Spacer(),
                    IconButton(
                      icon: Icon(
                        Icons.edit,
                        size: 20,
                        color: AppColors.primary,
                      ),
                      onPressed: () => _showEditTemplateDialog(
                        strings,
                        _selectedDay,
                        templateRanges,
                      ),
                      padding: EdgeInsets.zero,
                      constraints: const BoxConstraints(),
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 16),
          ] else ...[
            _buildSetupWorkingHours(strings, isDark),
            const SizedBox(height: 16),
          ],

          // Time slots section
          Text(
            strings.timeSlots,
            style: TextStyle(
              fontSize: 16,
              fontWeight: FontWeight.bold,
              color: isDark ? Colors.white : Colors.black87,
            ),
          ),
          const SizedBox(height: 8),

          if (daySlots.isEmpty)
            Center(
              child: Padding(
                padding: const EdgeInsets.all(32),
                child: Column(
                  children: [
                    Icon(
                      Icons.event_busy,
                      size: 48,
                      color: isDark ? Colors.white30 : Colors.grey.shade300,
                    ),
                    const SizedBox(height: 16),
                    Text(
                      strings.noSlotsForDay,
                      style: TextStyle(
                        color: isDark ? Colors.white54 : Colors.black45,
                      ),
                    ),
                  ],
                ),
              ),
            )
          else
            ...daySlots.map((slot) => _buildSlotCard(slot, strings, isDark)),
        ],
      ),
    );
  }

  Widget _buildSetupWorkingHours(S strings, bool isDark) {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: isDark ? AppColors.surfaceDark : Colors.grey.shade50,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(
          color: isDark ? AppColors.borderDark : AppColors.borderLight,
        ),
      ),
      child: Column(
        children: [
          Icon(
            Icons.schedule,
            size: 32,
            color: AppColors.primary.withValues(alpha: 0.7),
          ),
          const SizedBox(height: 12),
          Text(
            strings.setWorkingHours,
            style: TextStyle(
              fontWeight: FontWeight.w600,
              color: isDark ? Colors.white : Colors.black87,
            ),
          ),
          const SizedBox(height: 8),
          Text(
            strings.setWorkingHoursDesc,
            textAlign: TextAlign.center,
            style: TextStyle(
              fontSize: 13,
              color: isDark ? Colors.white60 : Colors.black54,
            ),
          ),
          const SizedBox(height: 16),
          OutlinedButton.icon(
            onPressed: () => _showEditTemplateDialog(
              ref.read(stringsProvider),
              _selectedDay,
              [],
            ),
            icon: const Icon(Icons.add),
            label: Text(strings.setWorkingHours),
          ),
        ],
      ),
    );
  }

  Widget _buildSlotCard(AvailabilitySlot slot, S strings, bool isDark) {
    final timeFormat = DateFormat('h:mm a');

    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      decoration: BoxDecoration(
        color: isDark ? AppColors.surfaceDark : Colors.white,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(
          color: slot.isBooked
              ? Colors.blue.withValues(alpha: 0.5)
              : (isDark ? AppColors.borderDark : AppColors.borderLight),
        ),
      ),
      child: ListTile(
        leading: Container(
          width: 4,
          height: 40,
          decoration: BoxDecoration(
            color: slot.isBooked
                ? Colors.blue
                : (slot.isPast ? Colors.grey : Colors.green),
            borderRadius: BorderRadius.circular(2),
          ),
        ),
        title: Text(
          '${timeFormat.format(slot.startTime)} - ${timeFormat.format(slot.endTime)}',
          style: TextStyle(
            fontWeight: FontWeight.w600,
            color: isDark ? Colors.white : Colors.black87,
          ),
        ),
        subtitle: Text(
          slot.isBooked
              ? strings.booked
              : (slot.isPast ? strings.past : strings.available),
          style: TextStyle(
            color: slot.isBooked
                ? Colors.blue
                : (slot.isPast ? Colors.grey : Colors.green),
          ),
        ),
        trailing: !slot.isBooked && !slot.isPast
            ? IconButton(
                icon: Icon(Icons.delete_outline, color: Colors.red.shade400),
                onPressed: () => _deleteSlot(slot, strings),
              )
            : null,
      ),
    );
  }

  bool _isToday(DateTime date) {
    final now = DateTime.now();
    return date.year == now.year &&
        date.month == now.month &&
        date.day == now.day;
  }

  void _showAddSlotDialog(S strings) {
    TimeOfDay startTime = const TimeOfDay(hour: 9, minute: 0);
    TimeOfDay endTime = const TimeOfDay(hour: 10, minute: 0);

    showDialog(
      context: context,
      builder: (context) => StatefulBuilder(
        builder: (context, setDialogState) => AlertDialog(
          title: Text(strings.addTimeSlot),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              ListTile(
                title: Text(strings.startTime),
                trailing: Text(startTime.format(context)),
                onTap: () async {
                  final picked = await showTimePicker(
                    context: context,
                    initialTime: startTime,
                  );
                  if (picked != null) {
                    setDialogState(() => startTime = picked);
                  }
                },
              ),
              ListTile(
                title: Text(strings.endTime),
                trailing: Text(endTime.format(context)),
                onTap: () async {
                  final picked = await showTimePicker(
                    context: context,
                    initialTime: endTime,
                  );
                  if (picked != null) {
                    setDialogState(() => endTime = picked);
                  }
                },
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: Text(strings.cancel),
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.pop(context);
                _addSlot(startTime, endTime, strings);
              },
              child: Text(strings.add),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _addSlot(
    TimeOfDay startTime,
    TimeOfDay endTime,
    S strings,
  ) async {
    final selectedDate = _selectedWeekStart.add(Duration(days: _selectedDay));
    final start = DateTime(
      selectedDate.year,
      selectedDate.month,
      selectedDate.day,
      startTime.hour,
      startTime.minute,
    );
    final end = DateTime(
      selectedDate.year,
      selectedDate.month,
      selectedDate.day,
      endTime.hour,
      endTime.minute,
    );

    if (end.isBefore(start) || end.isAtSameMomentAs(start)) {
      ScaffoldMessenger.of(
        context,
      ).showSnackBar(SnackBar(content: Text(strings.invalidTimeRange)));
      return;
    }

    setState(() => _isLoading = true);
    try {
      final authState = ref.read(authProvider);
      final service = ref.read(therapistAvailabilityServiceProvider);

      await service.addSlot(
        AvailabilitySlot(
          id: '',
          therapistId: authState.user!.uid,
          startTime: start,
          endTime: end,
          createdAt: DateTime.now(),
        ),
      );

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(strings.slotAdded),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(strings.errorOccurred),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  Future<void> _deleteSlot(AvailabilitySlot slot, S strings) async {
    final confirmed = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: Text(strings.deleteSlot),
        content: Text(strings.deleteSlotConfirm),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context, false),
            child: Text(strings.cancel),
          ),
          ElevatedButton(
            onPressed: () => Navigator.pop(context, true),
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.red,
              foregroundColor: Colors.white,
            ),
            child: Text(strings.delete),
          ),
        ],
      ),
    );

    if (confirmed == true) {
      try {
        final service = ref.read(therapistAvailabilityServiceProvider);
        await service.removeSlot(slot.id);

        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(strings.slotDeleted),
              backgroundColor: Colors.green,
            ),
          );
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(
            SnackBar(
              content: Text(strings.errorOccurred),
              backgroundColor: Colors.red,
            ),
          );
        }
      }
    }
  }

  void _showAutoGenerateDialog(S strings) {
    int weeks = 2;

    showDialog(
      context: context,
      builder: (context) => StatefulBuilder(
        builder: (context, setDialogState) => AlertDialog(
          title: Text(strings.autoGenerate),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Text(strings.autoGenerateDesc),
              const SizedBox(height: 16),
              DropdownButtonFormField<int>(
                initialValue: weeks,
                decoration: InputDecoration(
                  labelText: strings.numberOfWeeks,
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(8),
                  ),
                ),
                items: [1, 2, 3, 4]
                    .map(
                      (w) => DropdownMenuItem(
                        value: w,
                        child: Text('$w ${strings.weeks}'),
                      ),
                    )
                    .toList(),
                onChanged: (value) {
                  if (value != null) {
                    setDialogState(() => weeks = value);
                  }
                },
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: Text(strings.cancel),
            ),
            ElevatedButton(
              onPressed: () {
                Navigator.pop(context);
                _autoGenerateSlots(weeks, strings);
              },
              child: Text(strings.generate),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _autoGenerateSlots(int weeks, S strings) async {
    setState(() => _isLoading = true);
    try {
      final authState = ref.read(authProvider);
      final service = ref.read(therapistAvailabilityServiceProvider);

      final count = await service.autoGenerateSlots(authState.user!.uid, weeks);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('${strings.generated} $count ${strings.slots}'),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(
              e.toString().contains('No weekly template')
                  ? strings.setWorkingHoursFirst
                  : strings.errorOccurred,
            ),
            backgroundColor: Colors.red,
          ),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  void _showEditTemplateDialog(
    S strings,
    int day,
    List<TimeRange> currentRanges,
  ) {
    TimeOfDay startTime = const TimeOfDay(hour: 9, minute: 0);
    TimeOfDay endTime = const TimeOfDay(hour: 17, minute: 0);

    if (currentRanges.isNotEmpty) {
      startTime = TimeOfDay(
        hour: currentRanges.first.startHour,
        minute: currentRanges.first.startMinute,
      );
      endTime = TimeOfDay(
        hour: currentRanges.first.endHour,
        minute: currentRanges.first.endMinute,
      );
    }

    showDialog(
      context: context,
      builder: (context) => StatefulBuilder(
        builder: (context, setDialogState) => AlertDialog(
          title: Text('${strings.workingHours} - ${_getDayNames()[day]}'),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              ListTile(
                title: Text(strings.startTime),
                trailing: Text(startTime.format(context)),
                onTap: () async {
                  final picked = await showTimePicker(
                    context: context,
                    initialTime: startTime,
                  );
                  if (picked != null) {
                    setDialogState(() => startTime = picked);
                  }
                },
              ),
              ListTile(
                title: Text(strings.endTime),
                trailing: Text(endTime.format(context)),
                onTap: () async {
                  final picked = await showTimePicker(
                    context: context,
                    initialTime: endTime,
                  );
                  if (picked != null) {
                    setDialogState(() => endTime = picked);
                  }
                },
              ),
            ],
          ),
          actions: [
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: Text(strings.cancel),
            ),
            if (currentRanges.isNotEmpty)
              TextButton(
                onPressed: () {
                  Navigator.pop(context);
                  _clearDayTemplate(day, strings);
                },
                child: Text(
                  strings.clearDay,
                  style: const TextStyle(color: Colors.red),
                ),
              ),
            ElevatedButton(
              onPressed: () {
                Navigator.pop(context);
                _updateDayTemplate(day, startTime, endTime, strings);
              },
              child: Text(strings.save),
            ),
          ],
        ),
      ),
    );
  }

  Future<void> _updateDayTemplate(
    int day,
    TimeOfDay startTime,
    TimeOfDay endTime,
    S strings,
  ) async {
    try {
      final authState = ref.read(authProvider);
      final service = ref.read(therapistAvailabilityServiceProvider);

      final timeRange = TimeRange(
        startHour: startTime.hour,
        startMinute: startTime.minute,
        endHour: endTime.hour,
        endMinute: endTime.minute,
      );

      await service.updateDayAvailability(authState.user!.uid, day, [
        timeRange,
      ]);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(strings.workingHoursSaved),
            backgroundColor: Colors.green,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(strings.errorOccurred),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }

  Future<void> _clearDayTemplate(int day, S strings) async {
    try {
      final authState = ref.read(authProvider);
      final service = ref.read(therapistAvailabilityServiceProvider);

      await service.updateDayAvailability(authState.user!.uid, day, []);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(strings.dayClear),
            backgroundColor: Colors.orange,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text(strings.errorOccurred),
            backgroundColor: Colors.red,
          ),
        );
      }
    }
  }
}
