// File generated by flutterfire_cli.
// To regenerate this file, run:
// flutterfire configure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx1jmCuFECLCgdWoz0nuJuZ2Hcn-5kfgc',
    appId: '1:152690535180:android:36e8794ffd3174264a3729',
    messagingSenderId: '152690535180',
    projectId: 'sanad-app-beldify',
    storageBucket: 'sanad-app-beldify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCk1lzla88iqSM2ab_vqlXhbklHByFBUks',
    appId: '1:152690535180:ios:f097d70048389bc74a3729',
    messagingSenderId: '152690535180',
    projectId: 'sanad-app-beldify',
    storageBucket: 'sanad-app-beldify.firebasestorage.app',
    iosBundleId: 'com.sanad.sanadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCk1lzla88iqSM2ab_vqlXhbklHByFBUks',
    appId: '1:152690535180:ios:f097d70048389bc74a3729',
    messagingSenderId: '152690535180',
    projectId: 'sanad-app-beldify',
    storageBucket: 'sanad-app-beldify.firebasestorage.app',
    iosBundleId: 'com.sanad.sanadApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp8R7ZqqLgSopD29L6bj7KSwWzZQedagY',
    appId: '1:152690535180:web:5d34213b46a7f6b04a3729',
    messagingSenderId: '152690535180',
    projectId: 'sanad-app-beldify',
    authDomain: 'sanad-app-beldify.firebaseapp.com',
    storageBucket: 'sanad-app-beldify.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDp8R7ZqqLgSopD29L6bj7KSwWzZQedagY',
    appId: '1:152690535180:web:dcb337557e60477b4a3729',
    messagingSenderId: '152690535180',
    projectId: 'sanad-app-beldify',
    authDomain: 'sanad-app-beldify.firebaseapp.com',
    storageBucket: 'sanad-app-beldify.firebasestorage.app',
  );

}