import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/review.dart';
import '../repositories/review_repository.dart';

/// State class for review operations
class ReviewState {
  final bool isLoading;
  final bool isSubmitting;
  final String? errorMessage;
  final Review? currentReview;
  final List<Review> reviews;
  final bool submitted;

  const ReviewState({
    this.isLoading = false,
    this.isSubmitting = false,
    this.errorMessage,
    this.currentReview,
    this.reviews = const [],
    this.submitted = false,
  });

  ReviewState copyWith({
    bool? isLoading,
    bool? isSubmitting,
    String? errorMessage,
    Review? currentReview,
    List<Review>? reviews,
    bool? submitted,
    bool clearError = false,
  }) {
    return ReviewState(
      isLoading: isLoading ?? this.isLoading,
      isSubmitting: isSubmitting ?? this.isSubmitting,
      errorMessage: clearError ? null : (errorMessage ?? this.errorMessage),
      currentReview: currentReview ?? this.currentReview,
      reviews: reviews ?? this.reviews,
      submitted: submitted ?? this.submitted,
    );
  }
}

/// Provider for managing review state
class ReviewNotifier extends StateNotifier<ReviewState> {
  final ReviewRepository _repository;

  ReviewNotifier(this._repository) : super(const ReviewState());

  /// Submit a new review
  Future<bool> submitReview({
    required String therapistId,
    required String userId,
    required String bookingId,
    required double rating,
    String? comment,
  }) async {
    state = state.copyWith(isSubmitting: true, clearError: true);

    try {
      final review = Review(
        id: '', // Will be generated by Firestore
        therapistId: therapistId,
        userId: userId,
        bookingId: bookingId,
        rating: rating,
        comment: comment,
        createdAt: DateTime.now(),
      );

      await _repository.createReview(review);

      state = state.copyWith(
        isSubmitting: false,
        submitted: true,
        currentReview: review,
      );

      return true;
    } catch (e) {
      state = state.copyWith(
        isSubmitting: false,
        errorMessage: e.toString(),
      );
      return false;
    }
  }

  /// Load reviews for a therapist
  Future<void> loadTherapistReviews(String therapistId) async {
    state = state.copyWith(isLoading: true, clearError: true);

    try {
      final reviews = await _repository.getTherapistReviewsFuture(therapistId);
      state = state.copyWith(
        isLoading: false,
        reviews: reviews,
      );
    } catch (e) {
      state = state.copyWith(
        isLoading: false,
        errorMessage: e.toString(),
      );
    }
  }

  /// Check if user has already reviewed a booking
  Future<bool> checkExistingReview(String userId, String bookingId) async {
    try {
      return await _repository.hasUserReviewed(userId, bookingId);
    } catch (e) {
      return false;
    }
  }

  /// Get existing review for a booking
  Future<Review?> getBookingReview(String bookingId) async {
    try {
      return await _repository.getReviewByBooking(bookingId);
    } catch (e) {
      return null;
    }
  }

  /// Reset state
  void reset() {
    state = const ReviewState();
  }

  /// Clear error
  void clearError() {
    state = state.copyWith(clearError: true);
  }
}

/// Provider instance
final reviewProvider = StateNotifierProvider<ReviewNotifier, ReviewState>((ref) {
  final repository = ref.watch(reviewRepositoryProvider);
  return ReviewNotifier(repository);
});

/// Stream provider for therapist reviews
final therapistReviewsProvider = StreamProvider.family<List<Review>, String>(
  (ref, therapistId) {
    final repository = ref.watch(reviewRepositoryProvider);
    return repository.getTherapistReviews(therapistId);
  },
);

/// Future provider to check if booking has review
final hasReviewProvider = FutureProvider.family<bool, ({String userId, String bookingId})>(
  (ref, params) async {
    final repository = ref.watch(reviewRepositoryProvider);
    return repository.hasUserReviewed(params.userId, params.bookingId);
  },
);

/// Future provider for the actual review of a booking (if any)
final bookingReviewProvider = FutureProvider.family<Review?, String>(
  (ref, bookingId) async {
    if (bookingId.isEmpty) return null;
    final repository = ref.watch(reviewRepositoryProvider);
    return repository.getReviewByBooking(bookingId);
  },
);

/// Future provider for the set of booking IDs this user has already reviewed.
/// Used to filter unreviewed bookings in a single Firestore read.
final reviewedBookingIdsProvider = FutureProvider.family<Set<String>, String>(
  (ref, userId) async {
    if (userId.isEmpty) return const <String>{};
    final repository = ref.watch(reviewRepositoryProvider);
    return repository.getReviewedBookingIds(userId);
  },
);

/// Admin-only: fetch the free-text comment for a review.
/// Returns null for non-admins (rules block the read).
final reviewCommentProvider = FutureProvider.family<String?, String>(
  (ref, reviewId) async {
    if (reviewId.isEmpty) return null;
    final repository = ref.watch(reviewRepositoryProvider);
    return repository.getReviewComment(reviewId);
  },
);

/// Future provider for average rating
final averageRatingProvider = FutureProvider.family<double, String>(
  (ref, therapistId) async {
    final repository = ref.watch(reviewRepositoryProvider);
    return repository.getAverageRating(therapistId);
  },
);
